Tyler Fields

CSCI 4650

Homework #1

In [3]:
# Ex 0.1.2
# a. p(x) = 6x^3 - 2x^2 - 3x + 7 at x = -1/2
# Nested Form = ((6x - 2)x - 3)x + 7

x = -1/2

print(6 * x**3 - 2 * x**2 - 3 * x + 7)

# b. p(x) = 8x^5 - x^4 - 3x^3 + x^2 -3x + 1 at x = -1/2
# Nested Form = ((((8x - 1)x - 3)x - 1) x - 3)x + 1

print(8 * x**5 - x**4 - 3 * x**3 + x**2 - 3 * x + 1)

# c. p(x) = 4x^6 - 2x^4 - 2x + 4 at x = -1/2
# Nested Form = (((((4x)x - 2)x)x)x - 2)x + 4

print(4 * x**6 - 2 * x**4 - 2 * x + 4)

7.25
2.8125
4.9375


In [ ]:
# EX 0.1.6
# a. p(x) = a0 + a5x^5 + a10x^10 + a15x^15

# Reference
import numpy as np
a0 = -13; a5 = 26; a10 = 94; a15 = -2
x = np.array([-2, -1, 0, 1, 2])
px0 = a0 + a5 * (x**5) + a10 * (x**10) + a15 * (x**15)
print(px0)


# Implementation 1
x2 = x * x
x3 = x2 * x
x5 = x3 * x2
x10 = x5 * x5
x15 = x10 * x5

px1 = a0 + a5 * x5 + a10 * x10 + a15 * x15
print(px1)

# 8 multiplications, 3 additions, 0 power operators

# Implementation 2 (nested)
px3 = a0 + x5 * (a5 + x5 * (a10 + a15 * x5))
print(px3)

# 6 multiplications, 3 additions, 0 power operators

[160947     57    -13    105  31539]
[160947     57    -13    105  31539]
[160947     57    -13    105  31539]


In [1]:
# EX 0.1.6
# b. p(x) = a7x^7 + a12x^12 + a17x^17 + a22x^22 + a27x^27

# Reference
import numpy as np
a7 = 5; a12 = 2; a17 = 4; a22 = -2; a27 = 6
x = np.array([-2, -1, 0, 1, 2])
px0 = a7 * x**7 + a12 * x**12 + a22 * x**22 + a27 * x**27
print(px0)

#Implementation 1
x2 = x * x
x3 = x2 * x
x5 = x3 * x2
x7 = x5 * x2
x10 = x5 * x5

px1 = x7 * (a7 + x5 * (a12 + x10 * (a22 + a27 * x5)))
print(px1)

# 9 multiplications, 3 addititions, 0 power operators

[-813687424        -11          0         11  796926592]
[-813687424        -11          0         11  796926592]


In [2]:
# CP.0.1.2
# Use nest to evaluate p(x) = 1 - x + x^2 - x^3 + ... + x^98 - x^99 at x = 1.00001

import numpy as np

def polyval_nested(c, x):
  d = np.size(c)
  px = c[d - 1]
  for i in range(d - 2, -1, -1 ):
    px = px * x + c[i]
  return px

x = 1.00001
d = 99
c = np.ones([d+1])
px1 = polyval_nested(c, x)
print(px1)

# Simplified version
px2 = ((x ** (d + 1)) - 1) / (x - 1)
print(px2)


100.04951617392227
100.04951617391636
