Tyler Fields

CSCI 4650

Homework 3

In [ ]:
import numpy as np
import copy
from math import sqrt
import scipy
from scipy.optimize import fsolve
from scipy.optimize import root

In [ ]:
# ----------------------
# Exercise CP.2.2.1.b2c
# ----------------------

#
# useage:
#           L, U = lu_no_pivoting( A )
#
# performs LU_no_pivoting on `A`
#
# input:  A:       n-by-n matrix to be factored
# output: L an U:  the L and U factors defined by:
#                  (1) L is n-by-n lower unit triangular
#                  (2) U is n-by-n upper triangular
#                  (3) A = L * U
#
# warning: no pivoting is used, this algorithm will exit with error message if
# an exact-zero pivot is encountered, this code might be quite unstable when
# small pivots are encountered during the factorization.
#
# this is the standard in-place algorithm (so store L and U on top of A), but
# there is a deep copy of A so that the ``input A`` is not overwritten, in addition,
# we rewrite L and U in separate matrices
#
def lu_no_pivoting( A_ ):
  A = copy.deepcopy(A_)
#
  n = A.shape[0]
  for k in range(0,n-1):
    if ( A[k,k] == 0. ): print("oops, zero pivot encountered\n"); break
    for i in range(k+1,n):
      A[i,k] = A[i,k] / A[k,k]
      for j in range(k+1,n):
        A[i,j] = A[i,j] - A[k,j] * A[i,k]
#
  L = np.tril(A,-1)+np.eye(n)
  U = np.triu(A)
  return L, U

In [ ]:
# (b)
A = np.array([  [  4.,  2.,  0. ],
                [  4.,  4.,  2. ],
                [  2.,  2.,  3. ] ] )

# using our bucket algorithm `lu_no_pivoting`

L, U = lu_no_pivoting( A )

print("L=\n",L)
print("U=\n",U)

# check that A = LU
print("\nL @ U=\n", L @ U)
print("A=\n",A)
print("\n|| A - LU ||_oo / || A ||_oo = ", np.linalg.norm(A - L@U,np.inf)/np.linalg.norm(A,np.inf) )

L=
 [[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]
U=
 [[4. 2. 0.]
 [0. 2. 2.]
 [0. 0. 2.]]

L @ U=
 [[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]
A=
 [[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]

|| A - LU ||_oo / || A ||_oo =  0.0


In [ ]:
# (c)
A = np.array([  [  1., -1.,  1.,  2. ],
                [  0.,  2.,  1.,  0. ],
                [  1.,  3.,  4.,  4. ],
                [  0.,  2.,  1., -1. ]] )

# using our bucket algorithm `lu_no_pivoting`

L, U = lu_no_pivoting( A )

print("L=\n",L)
print("U=\n",U)

# check that A = LU
print("\nL @ U=\n", L @ U)
print("A=\n",A)
print("\n|| A - LU ||_oo / || A ||_oo = ", np.linalg.norm(A - L@U,np.inf)/np.linalg.norm(A,np.inf) )

L=
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 0. 1.]]
U=
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -1.]]

L @ U=
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 1.  3.  4.  4.]
 [ 0.  2.  1. -1.]]
A=
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 1.  3.  4.  4.]
 [ 0.  2.  1. -1.]]

|| A - LU ||_oo / || A ||_oo =  0.0


In [ ]:
# ---------------------
# Exercise CP.2.2.2.b
# ---------------------

#
# useage:
#           x = backward_substitution( A, b )
#
# performs backward substitution Ax = b where A is upper triangular
#
# input:  A and b: represent the upper triangular linear system of equations
#                  Ax=b we want to solve
# output: x:       solution of x of Ax=b (this is done in place)
#
# this is the standard in-place algorithm (so store x on top of b), but
# there is a deep copy of b so that the ``input b`` is not overwritten
#
def backward_substitution( A, b_ ):
  b = copy.deepcopy(b_)
  n = A.shape[0]
  for i in range(n-1,-1,-1):
    for j in range(i+1,n):
      b[i] = b[i] - A[i,j] * b[j]
    b[i] = b[i] / A[i,i]
  return b

# useage:
#           x = forward__substitution( A, b )
#
# performs forward substitution Ax = b where A is lower triangular
#
# input:  A and b: represent the lower triangular linear system of equations
#                 Ax=b we want to solve
# output: x:       solution of x of Ax=b (this is done in place)
#
# this is the standard in-place algorithm (so store x on top of b), but
# there is a deep copy of b so that the ``input b`` is not overwritten
#
def forward__substitution( A, b_ ):
  b = copy.deepcopy(b_)
  n = A.shape[0]
  for i in range(0,n,):
    for j in range(0,i):
      b[i] = b[i] - A[i,j] * b[j]
    b[i] = b[i] / A[i,i]
  return b

A = np.array([  [  4.,  2.,  0. ],
                [  4.,  4.,  2. ],
                [  2.,  2.,  3. ] ] )

b = np.array([  [  2. ],
                [  4. ],
                [  6. ] ] )

# solve Ax=b with np.linalg.solve
# and check that Ax is b

x = np.linalg.solve(A, b)

print("With np.linalg.solve, we find x = \n", x)

print("\nWe check that Ax is b. Indeed [ Ax, b ] =\n", np.concatenate((A@x, b), axis=1) )

print("\nrelative backward error: || b - Ax  ||_oo / || b ||_oo =\n", np.linalg.norm(b-A@x,np.inf)/np.linalg.norm(b,np.inf) )

# using our bucket algorithms
#   `lu_no_pivoting`
#   `forward__substitution`
#   `backward_substitution`

L, U = lu_no_pivoting( A )
y = forward__substitution( L, b )
x = backward_substitution( U, y )

print("With our algorithms, we find\n")
print("y=\n",y)
print("x=\n",x)

print("\nWe check that Ax is b. Indeed [ Ax, b ] =\n", np.concatenate((A@x, b), axis=1) )

print("\nrelative backward error: || b - Ax  ||_oo / || b ||_oo =\n", np.linalg.norm(b-A@x,np.inf)/np.linalg.norm(b,np.inf) )

With np.linalg.solve, we find x = 
 [[ 1.]
 [-1.]
 [ 2.]]

We check that Ax is b. Indeed [ Ax, b ] =
 [[2. 2.]
 [4. 4.]
 [6. 6.]]

relative backward error: || b - Ax  ||_oo / || b ||_oo =
 0.0
With our algorithms, we find

y=
 [[2.]
 [2.]
 [4.]]
x=
 [[ 1.]
 [-1.]
 [ 2.]]

We check that Ax is b. Indeed [ Ax, b ] =
 [[2. 2.]
 [4. 4.]
 [6. 6.]]

relative backward error: || b - Ax  ||_oo / || b ||_oo =
 0.0


In [ ]:
# ------------------
# Exercise EX.2.3.6
# ------------------

A = np.array([
                 [  1., 2.   ],
                 [  2., 4.01 ]])

b = np.array([[3.],[6.01]])

# Solution: x1 = 1 and x2 = 1
# Let us check this

x = np.array([[1.],[1.]])
print("|| b - Ax ||_oo / || b ||_oo = ",\
      f"{np.linalg.norm(b-A@x,np.inf)/np.linalg.norm(b,np.inf)}")

|| b - Ax ||_oo / || b ||_oo =  0.0


In [ ]:
# (e) What is the condition number of the coefficient matrix?

K = np.linalg.norm(A,np.inf)*np.linalg.norm(np.linalg.inv(A),np.inf)
print("kappa(A) = ", f"{K:6.1f}")

kappa(A) =  3612.0


In [ ]:
# Find the relative forward and backward errors and error magnification factor
# for the following approximate solutions of the system
# (a) [ -10 ]  (b) [ -100 ]  (c) [  -600 ]  (d) [ -599 ]
#     [   6 ]      [   52 ]      [   301 ]      [  301 ]

for xa in [ np.array([[-10.],[6.]]),\
            np.array([[-100.],[52.]]),\
            np.array([[-600.],[301.]]),\
            np.array([[-599.],[301.]]) ]:
  relative_forward_error = np.linalg.norm( x - xa, np.inf )\
     / np.linalg.norm( x, np.inf )
  relative_backward_error = np.linalg.norm( b - A@xa, np.inf )\
    / np.linalg.norm( b, np.inf )
  error_magnification_factor = relative_forward_error\
    / relative_backward_error
  print( "xa = [ ",f"{xa[0,0]:.0f}",",",f"{xa[1,0]:.0f}","]" )
  print( "relative forward error     = ",\
    f"{relative_forward_error:8.2f}" )
  print( "relative backward error    = ",\
    f"{relative_backward_error:8.2f}" )
  print( "error magnification factor = ",\
   f"{error_magnification_factor:8.2f}" )
  print("\n")

xa = [  -10 , 6 ]
relative forward error     =     11.00
relative backward error    =      0.32
error magnification factor =     33.90


xa = [  -100 , 52 ]
relative forward error     =    101.00
relative backward error    =      0.42
error magnification factor =    241.84


xa = [  -600 , 301 ]
relative forward error     =    601.00
relative backward error    =      0.17
error magnification factor =   3612.01


xa = [  -599 , 301 ]
relative forward error     =    600.00
relative backward error    =      0.50
error magnification factor =   1202.00




In [ ]:
# ------------------
# Exercise CP.2.3.4
# ------------------

n = 5
A = np.zeros( [ n, n ], dtype=float )
for i in range(0,n):
  for j in range(0,n):
    A[i,j] = sqrt( ( i - j )**2 + n / 10. )
print(A)

[[0.70710678 1.22474487 2.12132034 3.082207   4.0620192 ]
 [1.22474487 0.70710678 1.22474487 2.12132034 3.082207  ]
 [2.12132034 1.22474487 0.70710678 1.22474487 2.12132034]
 [3.082207   2.12132034 1.22474487 0.70710678 1.22474487]
 [4.0620192  3.082207   2.12132034 1.22474487 0.70710678]]


In [ ]:
%%time
for n in range(100,600,100):
  A = np.zeros( [ n, n ] )
  for i in range(0,n):
    for j in range(0,n):
      A[i,j] = sqrt( ( i - j )**2 + n / 10. )
  x = np.ones( [ n, 1 ] )
  b = A @ x

  xc = np.linalg.solve( A, b )

  relative_forward_error = np.linalg.norm( x - xc, np.inf )\
     / np.linalg.norm( x, np.inf )
  relative_backward_error = np.linalg.norm( b - A@xc, np.inf )\
    / np.linalg.norm( b, np.inf )
  error_magnification_factor = relative_forward_error\
    / relative_backward_error
  print( "n = ",f"{n:4d}" )
  print( "relative forward error                      = ",\
    f"{relative_forward_error:8.2e}" )
  print( "relative backward error                     = ",\
    f"{relative_backward_error:8.2e}" )
  print( "error magnification factor                  = ",\
   f"{error_magnification_factor:8.2e}" )
  print( "kappa( A ) = || A ||_oo * || A^{-1} ||_oo   = ",\
   f"{np.linalg.norm(A,np.inf) * np.linalg.norm(np.linalg.inv(A),np.inf):8.2e}")
  print("\n")

n =   100
relative forward error                      =  3.85e-09
relative backward error                     =  3.66e-16
error magnification factor                  =  1.05e+07
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  6.18e+07


n =   200
relative forward error                      =  8.30e-07
relative backward error                     =  5.47e-16
error magnification factor                  =  1.52e+09
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.29e+10


n =   300
relative forward error                      =  2.81e-05
relative backward error                     =  6.48e-16
error magnification factor                  =  4.34e+10
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  6.20e+11


n =   400
relative forward error                      =  8.34e-04
relative backward error                     =  9.11e-16
error magnification factor                  =  9.16e+11
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.48e+13


n =   500
relative forward error                      = 

In [ ]:
def lu_no_pivoting( A_, inplace = False ):
#
  if ( inplace ):
    A = A_
  else:
    A = copy.deepcopy(A_)
# begin main code
  n = A.shape[0]
  for k in range(0,n-1):
    if ( A[k,k] == 0. ): print("oops, zero pivot encountered\n"); break
    for i in range(k+1,n):
      A[i,k] = A[i,k] / A[k,k]
      for j in range(k+1,n):
        A[i,j] = A[i,j] - A[k,j] * A[i,k]
# end main code
  if not inplace:
    L = np.tril(A,-1)+np.eye(n)
    U = np.triu(A)
    return L, U

def backward_substitution( A, b_, inplace = False ):
#
  if ( inplace ):
    b = b_
  else:
    b = copy.deepcopy(b_)
#
  n = A.shape[0]
  for i in range(n-1,-1,-1):
    for j in range(i+1,n):
      b[i] = b[i] - A[i,j] * b[j]
    b[i] = b[i] / A[i,i]
#
  if not inplace:
    return b

def forward__substitution( A, b_, inplace = False, unit = False ):
  if ( inplace ):
    b = b_
  else:
    b = copy.deepcopy(b_)
#
  n = A.shape[0]
  for i in range(0,n,):
    for j in range(0,i):
      b[i] = b[i] - A[i,j] * b[j]
    if not unit:
      b[i] = b[i] / A[i,i]
#
  if not inplace:
    return b

In [ ]:
%%time
for n in range(100,600,100):
  A = np.zeros( [ n, n ] )
  for i in range(0,n):
    for j in range(0,n):
      A[i,j] = sqrt( ( i - j )**2 + n / 10. )
  x = np.ones( [ n, 1 ] )
  b = A @ x

  L, U = lu_no_pivoting( A )
  y = forward__substitution( L, b )
  xc = backward_substitution( U, y )

  relative_forward_error = np.linalg.norm( x - xc, np.inf )\
     / np.linalg.norm( x, np.inf )
  relative_backward_error = np.linalg.norm( b - A@xc, np.inf )\
    / np.linalg.norm( b, np.inf )
  error_magnification_factor = relative_forward_error\
    / relative_backward_error
  print( "n = ",f"{n:4d}" )
  print( "relative forward error                      = ",\
    f"{relative_forward_error:8.2e}" )
  print( "relative backward error                     = ",\
    f"{relative_backward_error:8.2e}" )
  print( "error magnification factor                  = ",\
   f"{error_magnification_factor:8.2e}" )
  print( "kappa( A ) = || A ||_oo * || A^{-1} ||_oo   = ",\
   f"{np.linalg.norm(A,np.inf) * np.linalg.norm(np.linalg.inv(A),np.inf):8.2e}")
  print("\n")

n =   100
relative forward error                      =  8.91e-08
relative backward error                     =  8.41e-15
error magnification factor                  =  1.06e+07
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  6.18e+07


n =   200
relative forward error                      =  2.57e-05
relative backward error                     =  2.94e-14
error magnification factor                  =  8.76e+08
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.29e+10


n =   300
relative forward error                      =  2.11e-03
relative backward error                     =  5.99e-14
error magnification factor                  =  3.53e+10
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  6.20e+11


n =   400
relative forward error                      =  3.40e-02
relative backward error                     =  4.41e-14
error magnification factor                  =  7.71e+11
kappa( A ) = || A ||_oo * || A^{-1} ||_oo   =  1.48e+13


n =   500
relative forward error                      = 

In [ ]:
# ----------------------
# Exercise CP.2.7.1.b2c
# ----------------------

# (b)  [  u^2 + 4v^2  =  4
#      [  4u^2 + v^2  =  4

F = lambda x : np.array( [ x[ 0 ]**2 + 4*x[ 1 ]**2 - 4., 4*x[ 0 ]**2 + x[ 1 ]**2 - 4. ] )

# Per EX.2.7.3.b, we have 4 exact solutions
x1 = np.array( [ 2./sqrt(5.), 2./sqrt(5.) ] )
x2 = np.array( [ -2./sqrt(5.), 2./sqrt(5.) ] )
x3 = np.array( [ 2./sqrt(5.), -2./sqrt(5.) ] )
x4 = np.array( [ -2./sqrt(5.), -2./sqrt(5.) ] )

# Let us check that || F(x1, x2, x3, x4) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )
print( "|| F(x3) ||_oo =", f"{np.linalg.norm(F(x3),np.inf):.2E}" )
print( "|| F(x4) ||_oo =", f"{np.linalg.norm(F(x4),np.inf):.2E}" )

# using scipy.optimize.root to find four approximate solutions

for x, x_ in zip( [ np.array( [  1.,  1. ] ),
                    np.array( [ -1.,  1. ] ),
                    np.array( [  1., -1. ] ),
                    np.array( [ -1., -1. ] ) ],
                  [ x1, x2, x3, x4 ] ):

  x = scipy.optimize.root( F, x ).x

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
        "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
         "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
         "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")

|| F(x1) ||_oo = 4.44E-16
|| F(x2) ||_oo = 4.44E-16
|| F(x3) ||_oo = 4.44E-16
|| F(x4) ||_oo = 4.44E-16

x = [  +0.8944271909999160 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999160 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  1.11e-16 
backward error: || F(x) ||_oo   =  8.88e-16

x = [  -0.8944271909998546 ]     x* = [  -0.8944271909999159 ]
    [  +0.8944271909999774 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  6.15e-14 
backward error: || F(x) ||_oo   =  3.30e-13

x = [  +0.8944271909999774 ]     x* = [  +0.8944271909999159 ]
    [  -0.8944271909998546 ]          [  -0.8944271909999159 ]
forward  error: || x - x* ||_oo =  6.15e-14 
backward error: || F(x) ||_oo   =  3.30e-13

x = [  -0.8944271909999160 ]     x* = [  -0.8944271909999159 ]
    [  -0.8944271909999160 ]          [  -0.8944271909999159 ]
forward  error: || x - x* ||_oo =  1.11e-16 
backward error: || F(x) ||_oo   =  8.88e-16


In [ ]:
# (c)  [       u^2 - 4v^2  =  4
#      [  (u - 1)^2 + v^2  =  4

F = lambda x : np.array( [ x[ 0 ]**2 - 4*x[ 1 ]**2 - 4., ( x[ 0 ] - 1. )**2 + x[ 1 ]**2 - 4. ] )

# Per EX.2.7.3.c, we have 2 exact solutions
x1 = np.array( [ 4/5*(1 + sqrt(6.)), 1/5*(sqrt(3 + 8*sqrt(6))) ] )
x2 = np.array( [ 4/5*(1 + sqrt(6.)), -1/5*(sqrt(3 + 8*sqrt(6))) ] )

# Let us check that || F(x1, x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )

# using scipy.optimize.root to find four approximate solutions

for x, x_ in zip( [ np.array( [ 3.,  1. ] ),
                    np.array( [ 3., -1. ] ) ],
                  [ x1, x2 ] ):

  x = scipy.optimize.root( F, x ).x

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
        "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
         "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
         "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")

|| F(x1) ||_oo = 8.88E-16
|| F(x2) ||_oo = 8.88E-16

x = [  +2.7595917942262052 ]     x* = [  +2.7595917942265427 ]
    [  +0.9507032753132335 ]          [  +0.9507032753128691 ]
forward  error: || x - x* ||_oo =  3.64e-13 
backward error: || F(x) ||_oo   =  4.63e-12

x = [  +2.7595917942262052 ]     x* = [  +2.7595917942265427 ]
    [  -0.9507032753132335 ]          [  -0.9507032753128691 ]
forward  error: || x - x* ||_oo =  3.64e-13 
backward error: || F(x) ||_oo   =  4.63e-12


In [ ]:
# ------------------
# Exercise CP.2.7.4
# ------------------

F = lambda x : np.array( [ 2*x[0]**2 - 4*x[0] + x[1]**2 + 3*x[2]**2 + 6*x[2] + 2,
                           x[0]**2 + x[1]**2 - 2*x[1] + 2*x[2]**2 - 5,
                           3*x[0]**2 - 12*x[0] + x[1]**2 + 3*x[2]**2 + 8 ] )

# check that
#    F( [  1. ] ) = [ 25. ]  and  F( [  3. ] ) = [ 57. ]
#       [ -1. ]     [  7. ]          [  5. ]     [ 51. ]
#       [  2. ]     [ 12. ]          [ -4. ]     [ 72. ]

print( F( np.array( [ 1., -1.,  2. ] ) ) )
print( F( np.array( [ 3.,  5., -4. ] ) ) )

# reference solutions

x1 = np.array( [   2.0000000000000000,  1.0000000000000000, -1.0000000000000000 ] )
x2 = np.array( [  +1.0960178410014330, -1.1592471842154839, -0.2611479367011116 ] )

for x in [ x1, x2 ]:

  print( "\nx = [", f"{x[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]")
  print( "    [", f"{x[2]:+20.16f}", "]")
  print( "backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")

[25.  7. 12.]
[57. 51. 72.]

x = [  +2.0000000000000000 ]
    [  +1.0000000000000000 ]
    [  -1.0000000000000000 ]
backward error: || F(x) ||_oo   =  0.00e+00

x = [  +1.0960178410014330 ]
    [  -1.1592471842154839 ]
    [  -0.2611479367011116 ]
backward error: || F(x) ||_oo   =  2.24e-11


In [ ]:
# Jacobian of F

def DF( x ):
  return np.array([[ 4*x[0]-4,    2*x[1],     6*x[2]+6 ],
                   [  2*x[0],     2*x[1]-2,   4*x[2]   ],
                   [  6*x[0]-12,  2*x[1],     6*x[2]   ]])

# check that
#   DF( [  1. ] ) = [  0., -2., 18. ]  and  DF( [  3. ] ) = [  8., 10., -18. ]
#       [ -1. ]     [  2., -4.,  8. ]           [  5. ]     [  6.,  8., -16. ]
#       [  2. ]     [ -6., -2., 12. ]           [ -4. ]     [  6., 10., -24. ]

print( DF( np.array( [ 1., -1.,  2. ] ) ) )
print( DF( np.array( [ 3.,  5., -4. ] ) ) )

[[ 0. -2. 18.]
 [ 2. -4.  8.]
 [-6. -2. 12.]]
[[  8.  10. -18.]
 [  6.   8. -16.]
 [  6.  10. -24.]]


In [ ]:
for x, x_ in zip( [ np.array( [ 3., 2., 0. ] ), np.array( [ 1., -1., 0. ] ) ],
                  [ x1, x2 ] ):

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}", f"{x[2]:+20.16f}",\
       "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
      f"{np.linalg.norm( F(x), np.inf):4.1e}" )

# Newton's method loop
  for i in range(1,10):

# Newton's method update
    x = x - np.linalg.solve( DF(x), F(x) )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}", f"{x[2]:+20.16f}",\
           "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
          f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
        "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
         "          [", f"{x_[1]:+20.16f}", "]")
  print( "    [", f"{x[2]:+20.16f}", "]"\
         "          [", f"{x_[2]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
         "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")

 0 [  +3.0000000000000000  +2.0000000000000000  +0.0000000000000000 ] 1.0e+00 1.2e+01
 1 [  +2.1666666666666670  +2.5000000000000000  -1.2222222222222223 ] 1.5e+00 6.8e+00
 2 [  +2.2195856297203505  +1.2487752602571960  -1.1388208477920663 ] 2.5e-01 1.6e+00
 3 [  +2.0115800108871564  +1.0589495220933967  -1.0149087140604431 ] 5.9e-02 2.1e-01
 4 [  +2.0005732239172462  +1.0009701198438699  -1.0004022860737878 ] 9.7e-04 4.4e-03
 5 [  +2.0000002059081754  +1.0000006290087016  -1.0000001919970494 ] 6.3e-07 2.4e-06
 6 [  +2.0000000000000728  +1.0000000000001499  -1.0000000000000553 ] 1.5e-13 6.3e-13
 7 [  +2.0000000000000000  +1.0000000000000002  -0.9999999999999998 ] 2.2e-16 1.8e-15
 8 [  +2.0000000000000000  +0.9999999999999998  -1.0000000000000002 ] 2.2e-16 1.8e-15
 9 [  +2.0000000000000000  +1.0000000000000002  -0.9999999999999998 ] 2.2e-16 1.8e-15

x = [  +2.0000000000000000 ]     x* = [  +2.0000000000000000 ]
    [  +1.0000000000000002 ]          [  +1.0000000000000000 ]
    [  -0.999

In [ ]:
# --------------------
# Exercise CP.2.7.5.b
# --------------------

# (b) Each sphere has radius 5, with centers
#    (  1, -2,  0 ),
#    ( -2,  2, -1 ),
#    (  4, -2,  3 ).

F = lambda x : np.array( [
                          ( x[0] - 1. )**2 + ( x[1] + 2. )**2  + ( x[2]      )**2  - 25.,
                          ( x[0] + 2. )**2 + ( x[1] - 2. )**2  + ( x[2] + 1. )**2  - 25.,
                          ( x[0] - 4. )**2 + ( x[1] + 2. )**2  + ( x[2] - 3. )**2  - 25. ] )

# Per Sauer, we have two exact solutions x1 and x2 such that
x1 = np.array( [ 1.,      2.,      3.     ] )
x2 = np.array( [ 17./9.,  22./9.,  19./9. ] )

# Let us check that || F(x1) ||_oo and || F(x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )

|| F(x1) ||_oo = 0.00E+00
|| F(x2) ||_oo = 3.55E-15


In [ ]:
# using scipy.optimize.fsolve to find two approximate solutions

# take the initial guess (0,0,0)
# we get an approximate solution, we call it x1

x = np.array( [ 0., 0., 0. ] )

x = scipy.optimize.fsolve( F, x )

print( "\nx = [", f"{x[0]:+20.16f}", "]")
print( "    [", f"{x[1]:+20.16f}", "]")
print( "    [", f"{x[2]:+20.16f}", "]")
print( "backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")

# take another initial guess (1, -2, 0)
# we get an approximate solution, we call it x2
# making sure that x2 is not x1

x = np.array( [ 1., -2., 0. ] )

x = scipy.optimize.fsolve( F, x )

print( "\nx = [", f"{x[0]:+20.16f}", "]")
print( "    [", f"{x[1]:+20.16f}", "]")
print( "    [", f"{x[2]:+20.16f}", "]")
print( "backward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")


x = [  +1.8888888888888751 ]
    [  +2.4444444444444366 ]
    [  +2.1111111111111254 ]
backward error: || F(x) ||_oo   =  3.55e-14

x = [  +1.0000000000000031 ]
    [  +2.0000000000000013 ]
    [  +2.9999999999999973 ]
backward error: || F(x) ||_oo   =  3.55e-15


In [ ]:
# Jacobian of F

DF = lambda x : np.array([
  [ 2. * x[0] - 2., 2. * x[1] + 4., 2. * x[2]      ],
  [ 2. * x[0] + 4., 2. * x[1] - 4., 2. * x[2] + 2. ],
  [ 2. * x[0] - 8., 2. * x[1] + 4., 2. * x[2] - 6. ] ])

for x, x_ in zip( [ np.array( [ 0.8, 1.8, 2.7 ] ), np.array( [ 2.0, 2.5, 2.0 ] ) ],
                  [ x2, x1 ] ):

  print( f"{0:2d}", "[", f"{x[0]:+18.14f}", f"{x[1]:+18.14f}",\
         f"{x[2]:+18.14f}",\
       "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
      f"{np.linalg.norm( F(x), np.inf):4.1e}" )

# this is the Newton's method loop, 8 iterations should be enough
  for i in range(1,8):

#   this is the Newton's method update
    x = x - np.linalg.solve( DF(x), F(x) )

    print( f"{i:2d}", "[", f"{x[0]:+18.14f}",\
           f"{x[1]:+18.14f}", f"{x[2]:+18.14f}",\
           "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
          f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+18.14f}", "]"\
        "     x* = [", f"{x_[0]:+18.14f}", "]")
  print( "    [", f"{x[1]:+18.14f}", "]"\
         "          [", f"{x_[1]:+18.14f}", "]")
  print( "    [", f"{x[2]:+18.14f}", "]"\
         "          [", f"{x_[2]:+18.14f}", "]")
  print( "forward  error: || x - x* ||_oo = ",\
 f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
         "\nbackward error: || F(x) ||_oo   = ",\
 f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")

 0 [  +0.80000000000000  +1.80000000000000  +2.70000000000000 ] 3.0e-01 3.4e+00
 1 [  +0.91500000000000  +1.95750000000000  +3.08500000000000 ] 8.5e-02 1.9e-01
 2 [  +0.99317681007345  +1.99658840503672  +3.00682318992655 ] 6.8e-03 1.4e-02
 3 [  +0.99994841650805  +1.99997420825403  +3.00005158349195 ] 5.2e-05 1.0e-04
 4 [  +0.99999999700689  +1.99999999850344  +3.00000000299311 ] 3.0e-09 6.0e-09
 5 [  +1.00000000000000  +2.00000000000000  +3.00000000000000 ] 4.4e-16 0.0e+00
 6 [  +1.00000000000000  +2.00000000000000  +3.00000000000000 ] 4.4e-16 0.0e+00
 7 [  +1.00000000000000  +2.00000000000000  +3.00000000000000 ] 4.4e-16 0.0e+00

x = [  +1.00000000000000 ]     x* = [  +1.00000000000000 ]
    [  +2.00000000000000 ]          [  +2.00000000000000 ]
    [  +3.00000000000000 ]          [  +3.00000000000000 ]
forward  error: || x - x* ||_oo =  4.44e-16 
backward error: || F(x) ||_oo   =  0.00e+00


 0 [  +2.00000000000000  +2.50000000000000  +2.00000000000000 ] 1.1e-01 2.5e-01
 1 [  +1.90

In [ ]:
# ----------------------
# Exercise CP.2.7.7.b2c
# ----------------------

# (b)  [  u^2 + 4v^2  =  4
#      [  4u^2 + v^2  =  4

F = lambda x : np.array( [ x[ 0 ]**2 + 4*x[ 1 ]**2 - 4., 4*x[ 0 ]**2 + x[ 1 ]**2 - 4. ] )

# Per EX.2.7.3.b, we have 4 exact solutions
x1 = np.array( [ 2./sqrt(5.), 2./sqrt(5.) ] )
x2 = np.array( [ -2./sqrt(5.), 2./sqrt(5.) ] )
x3 = np.array( [ 2./sqrt(5.), -2./sqrt(5.) ] )
x4 = np.array( [ -2./sqrt(5.), -2./sqrt(5.) ] )

# Let us check that || F(x1, x2, x3, x4) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )
print( "|| F(x3) ||_oo =", f"{np.linalg.norm(F(x3),np.inf):.2E}" )
print( "|| F(x4) ||_oo =", f"{np.linalg.norm(F(x4),np.inf):.2E}" )

|| F(x1) ||_oo = 4.44E-16
|| F(x2) ||_oo = 4.44E-16
|| F(x3) ||_oo = 4.44E-16
|| F(x4) ||_oo = 4.44E-16


In [ ]:
for x, x_ in zip( [ np.array( [ 0.8, 0.8 ] ), np.array( [ -0.85, 0.85 ] ), np.array( [ 0.85, -0.85 ] ), np.array( [ -0.8, -0.8 ] ) ],
                  [ x1, x2, x3, x4 ] ):
  A = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  for i in range(1,12):

    x0 = x
    x = x - np.linalg.solve( A, F(x) )
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    A = A + np.outer ( ( Delta - ( A @ delta ) ), delta / (delta.T @ delta) )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")

 0 [  +0.8000000000000000  +0.8000000000000000 ] 9.4e-02 8.0e-01
 1 [  +1.5999999999999994  +1.5999999999999994 ] 7.1e-01 8.8e+00
 2 [  +0.8666666666666668  +0.8666666666666665 ] 2.8e-02 2.4e-01
 3 [  +0.8864864864864878  +0.8864864864864852 ] 7.9e-03 7.1e-02
 4 [  +0.8945529290853141  +0.8945529290852923 ] 1.3e-04 1.1e-03
 5 [  +0.8944266304009469  +0.8944266304008097 ] 5.6e-07 5.0e-06
 6 [  +0.8944271909609495  +0.8944271909600792 ] 4.0e-11 3.5e-10
 7 [  +0.8944271910026866  +0.8944271909971451 ] 2.8e-12 1.5e-11
 8 [  +0.8944271910178956  +0.8944271909819361 ] 1.8e-11 9.6e-11
 9 [  +0.8944271909999157  +0.8944271909999160 ] 1.1e-16 8.9e-16
10 [  +0.8944271909999159  +0.8944271909999160 ] 1.1e-16 8.9e-16
11 [  +0.8944271909999159  +0.8944271909999157 ] 1.1e-16 1.3e-15

x = [  +0.8944271909999159 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999157 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  1.11e-16 
backward error: || F(x) ||_oo   =  1.33e-15
 0 [

/tmp/ipykernel_3991/2455883879.py:15: RuntimeWarning: invalid value encountered in divide
  A = A + np.outer ( ( Delta - ( A @ delta ) ), delta / (delta.T @ delta) )


In [ ]:
# (c)  [       u^2 - 4v^2  =  4
#      [  (u - 1)^2 + v^2  =  4

F = lambda x : np.array( [ x[ 0 ]**2 - 4*x[ 1 ]**2 - 4., ( x[ 0 ] - 1. )**2 + x[ 1 ]**2 - 4. ] )

# Per EX.2.7.3.c, we have 2 exact solutions
x1 = np.array( [ 4/5*(1 + sqrt(6.)), 1/5*(sqrt(3 + 8*sqrt(6))) ] )
x2 = np.array( [ 4/5*(1 + sqrt(6.)), -1/5*(sqrt(3 + 8*sqrt(6))) ] )

# Let us check that || F(x1, x2) ||_oo are small
print( "|| F(x1) ||_oo =", f"{np.linalg.norm(F(x1),np.inf):.2E}" )
print( "|| F(x2) ||_oo =", f"{np.linalg.norm(F(x2),np.inf):.2E}" )

|| F(x1) ||_oo = 8.88E-16
|| F(x2) ||_oo = 8.88E-16


In [ ]:
for x, x_ in zip( [ np.array( [ 2.7, 0.9 ] ), np.array( [ 2.7, -0.9 ] ) ],
                  [ x1, x2 ] ):
  A = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  for i in range(1,12):

    x0 = x
    x = x - np.linalg.solve( A, F(x) )
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    A = A + np.outer ( ( Delta - ( A @ delta ) ), delta / (delta.T @ delta) )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")

 0 [  +2.7000000000000002  +0.9000000000000000 ] 6.0e-02 3.0e-01
 1 [  +2.6499999999999995  +1.1999999999999993 ] 2.5e-01 2.7e+00
 2 [  +3.5604494382022409  +1.1459550561797760 ] 8.0e-01 3.9e+00
 3 [  +2.6940678610893576  +0.9293568291753278 ] 6.6e-02 2.7e-01
 4 [  +2.7488775055838390  +0.9466233734612807 ] 1.1e-02 4.5e-02
 5 [  +2.7599355988996486  +0.9507587235087386 ] 3.4e-04 1.5e-03
 6 [  +2.7596060091151258  +0.9507005710433166 ] 1.4e-05 9.9e-05
 7 [  +2.7595929535370542  +0.9507031016114047 ] 1.2e-06 7.7e-06
 8 [  +2.7595917827450727  +0.9507032770400350 ] 1.1e-08 7.7e-08
 9 [  +2.7595917942250106  +0.9507032753130980 ] 1.5e-12 1.0e-11
10 [  +2.7595917942265427  +0.9507032753128690 ] 1.1e-16 1.8e-15
11 [  +2.7595917942265427  +0.9507032753128691 ] 0.0e+00 8.9e-16

x = [  +2.7595917942265427 ]     x* = [  +2.7595917942265427 ]
    [  +0.9507032753128691 ]          [  +0.9507032753128691 ]
forward  error: || x - x* ||_oo =  0.00e+00 
backward error: || F(x) ||_oo   =  8.88e-16
 0 [

In [ ]:
# ----------------------
# Exercise CP.2.7.8.b2c
# ----------------------

# (b)  [  u^2 + 4v^2  =  4
#      [  4u^2 + v^2  =  4

F = lambda x : np.array( [ x[ 0 ]**2 + 4*x[ 1 ]**2 - 4., 4*x[ 0 ]**2 + x[ 1 ]**2 - 4. ] )

# Per EX.2.7.3.b, we have 4 exact solutions
x1 = np.array( [ 2./sqrt(5.), 2./sqrt(5.) ] )
x2 = np.array( [ -2./sqrt(5.), 2./sqrt(5.) ] )
x3 = np.array( [ 2./sqrt(5.), -2./sqrt(5.) ] )
x4 = np.array( [ -2./sqrt(5.), -2./sqrt(5.) ] )

In [ ]:
for x, x_ in zip( [ np.array( [ 0.85, 0.85 ] ), np.array( [ -0.85, 0.85 ] ), np.array( [ 0.85, -0.85 ] ), np.array( [ -0.85, -0.85 ] ) ],
                  [ x1, x2, x3, x4 ] ):

  B = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  for i in range(1,12):

    x0 = x
    x = x - B @ F(x)
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    denom = delta.T @ ( B @ Delta )
    if abs(denom) > 1e-14:
        B = B + np.outer ( ( delta - ( B @ Delta ) ), ( delta.T @ B ) / denom )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")

 0 [  +0.8500000000000000  +0.8500000000000000 ] 4.4e-02 3.9e-01
 1 [  +1.2375000000000003  +1.2375000000000003 ] 3.4e-01 3.7e+00
 2 [  +0.8871257485029935  +0.8871257485029935 ] 7.3e-03 6.5e-02
 3 [  +0.8932481944689096  +0.8932481944689096 ] 1.2e-03 1.1e-02
 4 [  +0.8944320261500871  +0.8944320261500871 ] 4.8e-06 4.3e-05
 5 [  +0.8944271878110763  +0.8944271878110763 ] 3.2e-09 2.9e-08
 6 [  +0.8944271909999073  +0.8944271909999073 ] 8.5e-15 7.7e-14
 7 [  +0.8944271909999159  +0.8944271909999159 ] 0.0e+00 4.4e-16
 8 [  +0.8944271909999159  +0.8944271909999159 ] 0.0e+00 4.4e-16
 9 [  +0.8944271909999159  +0.8944271909999159 ] 0.0e+00 4.4e-16
10 [  +0.8944271909999159  +0.8944271909999159 ] 0.0e+00 4.4e-16
11 [  +0.8944271909999159  +0.8944271909999159 ] 0.0e+00 4.4e-16

x = [  +0.8944271909999159 ]     x* = [  +0.8944271909999159 ]
    [  +0.8944271909999159 ]          [  +0.8944271909999159 ]
forward  error: || x - x* ||_oo =  0.00e+00 
backward error: || F(x) ||_oo   =  4.44e-16


 0

In [ ]:
# (c)  [       u^2 - 4v^2  =  4
#      [  (u - 1)^2 + v^2  =  4

F = lambda x : np.array( [ x[ 0 ]**2 - 4*x[ 1 ]**2 - 4., ( x[ 0 ] - 1. )**2 + x[ 1 ]**2 - 4. ] )

# Per EX.2.7.3.c, we have 2 exact solutions
x1 = np.array( [ 4/5*(1 + sqrt(6.)), 1/5*(sqrt(3 + 8*sqrt(6))) ] )
x2 = np.array( [ 4/5*(1 + sqrt(6.)), -1/5*(sqrt(3 + 8*sqrt(6))) ] )

In [ ]:
for x, x_ in zip( [ np.array( [ 2.7, 0.9 ] ), np.array( [ 2.7, -0.9 ] ) ],
                  [ x1, x2 ] ):

  B = np.eye(2,2)

  print( f"{0:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
        "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}", \
        f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  for i in range(1,12):

    x0 = x
    x = x - B @ F(x)
    Delta = ( F(x) - F(x0) )
    delta = x - x0
    B = B + np.outer ( ( delta - ( B @ Delta ) ), ( delta.T @ B ) / (delta.T @ ( B @ Delta) ) )

    print( f"{i:2d}", "[", f"{x[0]:+20.16f}", f"{x[1]:+20.16f}",\
            "]", f"{np.linalg.norm( x - x_, np.inf):4.1e}",\
            f"{np.linalg.norm( F(x), np.inf):4.1e}" )

  print( "\nx = [", f"{x[0]:+20.16f}", "]"\
          "     x* = [", f"{x_[0]:+20.16f}", "]")
  print( "    [", f"{x[1]:+20.16f}", "]"\
          "          [", f"{x_[1]:+20.16f}", "]")
  print( "forward  error: || x - x* ||_oo = ", f"{np.linalg.norm(x-x_,np.inf):7.2e}",\
          "\nbackward error: || F(x) ||_oo   = ", f"{np.linalg.norm(F(x),np.inf):7.2e}")
  print("\n")

 0 [  +2.7000000000000002  +0.9000000000000000 ] 6.0e-02 3.0e-01
 1 [  +2.6499999999999995  +1.1999999999999993 ] 2.5e-01 2.7e+00
 2 [  +3.5604494382022409  +1.1459550561797760 ] 8.0e-01 3.9e+00
 3 [  +2.6940678610893567  +0.9293568291753280 ] 6.6e-02 2.7e-01
 4 [  +2.7488775055838386  +0.9466233734612806 ] 1.1e-02 4.5e-02
 5 [  +2.7599355988996486  +0.9507587235087385 ] 3.4e-04 1.5e-03
 6 [  +2.7596060091151258  +0.9507005710433167 ] 1.4e-05 9.9e-05
 7 [  +2.7595929535370542  +0.9507031016114048 ] 1.2e-06 7.7e-06
 8 [  +2.7595917827450727  +0.9507032770400350 ] 1.1e-08 7.7e-08
 9 [  +2.7595917942250106  +0.9507032753130980 ] 1.5e-12 1.0e-11
10 [  +2.7595917942265427  +0.9507032753128690 ] 1.1e-16 1.8e-15
11 [  +2.7595917942265427  +0.9507032753128691 ] 0.0e+00 8.9e-16

x = [  +2.7595917942265427 ]     x* = [  +2.7595917942265427 ]
    [  +0.9507032753128691 ]          [  +0.9507032753128691 ]
forward  error: || x - x* ||_oo =  0.00e+00 
backward error: || F(x) ||_oo   =  8.88e-16


 0